### ISSUE TITLE
Cannot find subscription

### ISSUE THREAD

**Issue by SidGrundfos** [yesoreyeram/grafana-dashboards#2]
I have created an azure monitor datasource, I do not have log analytics or App Insights. I am geting an error that subscription does not exist. Do you have any docs on how to configure the azure side? Do we need all 3 azure monitor, log analytics and application insights?

**Comment by yesoreyeram** [comment]
This question is more related to the azure datasource. So i would suggest you to open an issue with grafana or checkout with friendly community in slack.
